// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package oss_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OssAppConfig is the golang structure of table oss_app_config for DAO operations like Where/Data.
type OssAppConfig struct {
	g.Meta          `orm:"table:oss_app_config, do:true"`
	Id              interface{} //
	AppName         interface{} // 应用名称
	AvailableNumber interface{} // 可用总量
	CurrentLimiting interface{} // 总量
	UseNumber       interface{} // 使用量
	StartTime       *gtime.Time // 生效时间
	EndTime         *gtime.Time // 失效时间
	Status          interface{} // 状态：0禁用 1正常
	Remark          interface{} // 备注
	UnionMainId     interface{} // 主体id
	BucketId        interface{} // 存储空间id
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
	DeletedAt       *gtime.Time //
}
