// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package oss_do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// OssServiceProviderConfig is the golang structure of table oss_service_provider_config for DAO operations like Where/Data.
type OssServiceProviderConfig struct {
	g.Meta          `orm:"table:oss_service_provider_config, do:true"`
	Id              interface{} //
	ProviderName    interface{} // 渠道商名称
	ProviderNo      interface{} // 渠道商编号
	AccessKeyId     interface{} // 身份标识
	AccessKeySecret interface{} // 身份认证密钥
	Token           interface{} // 安全令牌
	BasePath        interface{} // 域名
	Endpoint        interface{} // bucket调用域名
	Remark          interface{} // 备注
	Status          interface{} // 状态：0禁用 1启用
	ExtJson         interface{} // 拓展字段
	Region          interface{} // 地域
	CreatedAt       *gtime.Time //
	UpdatedAt       *gtime.Time //
	DeletedAt       *gtime.Time //
}
