// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package oss_dao

import (
	"github.com/kysion/base-library/utility/daoctl/dao_interface"
	"github.com/kysion/oss-library/oss_model/oss_dao/internal"
)

type OssServiceProviderConfigDao = dao_interface.TIDao[internal.OssServiceProviderConfigColumns]

func NewOssServiceProviderConfig(dao ...dao_interface.IDao) OssServiceProviderConfigDao {
	return (OssServiceProviderConfigDao)(internal.NewOssServiceProviderConfigDao(dao...))
}

var (
	OssServiceProviderConfig = NewOssServiceProviderConfig()
)
