// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package oss_entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// OssAppConfig is the golang structure for table oss_app_config.
type OssAppConfig struct {
	Id              int64       `json:"id"              description:""`
	AppName         string      `json:"appName"         description:"应用名称"`
	AvailableNumber int64       `json:"availableNumber" description:"可用总量"`
	CurrentLimiting int64       `json:"currentLimiting" description:"总量"`
	UseNumber       int64       `json:"useNumber"       description:"使用量"`
	StartTime       *gtime.Time `json:"startTime"       description:"生效时间"`
	EndTime         *gtime.Time `json:"endTime"         description:"失效时间"`
	Status          int         `json:"status"          description:"状态：0禁用 1正常"`
	Remark          string      `json:"remark"          description:"备注"`
	UnionMainId     int64       `json:"unionMainId"     description:"主体id"`
	BucketId        int64       `json:"bucketId"        description:"存储空间id"`
	CreatedAt       *gtime.Time `json:"createdAt"       description:""`
	UpdatedAt       *gtime.Time `json:"updatedAt"       description:""`
	DeletedAt       *gtime.Time `json:"deletedAt"       description:""`
}
