// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// OssServiceProviderConfigDao is the data access object for table oss_service_provider_config.
type OssServiceProviderConfigDao struct {
	dao_interface.IDao
	table       string                          // table is the underlying table name of the DAO.
	group       string                          // group is the database configuration group name of current DAO.
	columns     OssServiceProviderConfigColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// OssServiceProviderConfigColumns defines and stores column names for table oss_service_provider_config.
type OssServiceProviderConfigColumns struct {
	Id              string //
	ProviderName    string // 渠道商名称
	ProviderNo      string // 渠道商编号
	AccessKeyId     string // 身份标识
	AccessKeySecret string // 身份认证密钥
	Token           string // 安全令牌
	Endpoint        string // Bucket的地域域名
	Remark          string // 备注
	Status          string // 状态：0禁用 1启用
	ExtJson         string // 拓展字段
	Region          string // 地域
	CreatedAt       string //
	UpdatedAt       string //
	DeletedAt       string //
	Priority        string // 优先级，使用默认选择优先级最高的
}

// ossServiceProviderConfigColumns holds the columns for table oss_service_provider_config.
var ossServiceProviderConfigColumns = OssServiceProviderConfigColumns{
	Id:              "id",
	ProviderName:    "provider_name",
	ProviderNo:      "provider_no",
	AccessKeyId:     "access_key_id",
	AccessKeySecret: "access_key_secret",
	Token:           "token",
	Endpoint:        "endpoint",
	Remark:          "remark",
	Status:          "status",
	ExtJson:         "ext_json",
	Region:          "region",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
	Priority:        "priority",
}

// NewOssServiceProviderConfigDao creates and returns a new DAO object for table data access.
func NewOssServiceProviderConfigDao(proxy ...dao_interface.IDao) *OssServiceProviderConfigDao {
	var dao *OssServiceProviderConfigDao
	if len(proxy) > 0 {
		dao = &OssServiceProviderConfigDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     ossServiceProviderConfigColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &OssServiceProviderConfigDao{
		group:   "default",
		table:   "oss_service_provider_config",
		columns: ossServiceProviderConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OssServiceProviderConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *OssServiceProviderConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *OssServiceProviderConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *OssServiceProviderConfigDao) Columns() OssServiceProviderConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OssServiceProviderConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *OssServiceProviderConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OssServiceProviderConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *OssServiceProviderConfigDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *OssServiceProviderConfigDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *OssServiceProviderConfigDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *OssServiceProviderConfigDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
