// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/kysion/base-library/utility/daoctl"
	"github.com/kysion/base-library/utility/daoctl/dao_interface"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// OssAppConfigDao is the data access object for table oss_app_config.
type OssAppConfigDao struct {
	dao_interface.IDao
	table       string              // table is the underlying table name of the DAO.
	group       string              // group is the database configuration group name of current DAO.
	columns     OssAppConfigColumns // columns contains all the column names of Table for convenient usage.
	daoConfig   *dao_interface.DaoConfig
	ignoreCache bool
	exWhereArr  []string
}

// OssAppConfigColumns defines and stores column names for table oss_app_config.
type OssAppConfigColumns struct {
	Id              string //
	AppName         string // 应用名称
	AvailableNumber string // 可用总量
	CurrentLimiting string // 总量
	UseNumber       string // 使用量
	StartTime       string // 生效时间
	EndTime         string // 失效时间
	Status          string // 状态：0禁用 1正常
	Remark          string // 备注
	UnionMainId     string // 主体id
	BucketId        string // 存储空间id
	CreatedAt       string //
	UpdatedAt       string //
	DeletedAt       string //
}

// ossAppConfigColumns holds the columns for table oss_app_config.
var ossAppConfigColumns = OssAppConfigColumns{
	Id:              "id",
	AppName:         "app_name",
	AvailableNumber: "available_number",
	CurrentLimiting: "current_limiting",
	UseNumber:       "use_number",
	StartTime:       "start_time",
	EndTime:         "end_time",
	Status:          "status",
	Remark:          "remark",
	UnionMainId:     "union_main_id",
	BucketId:        "bucket_id",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
	DeletedAt:       "deleted_at",
}

// NewOssAppConfigDao creates and returns a new DAO object for table data access.
func NewOssAppConfigDao(proxy ...dao_interface.IDao) *OssAppConfigDao {
	var dao *OssAppConfigDao
	if len(proxy) > 0 {
		dao = &OssAppConfigDao{
			group:       proxy[0].Group(),
			table:       proxy[0].Table(),
			columns:     ossAppConfigColumns,
			daoConfig:   proxy[0].DaoConfig(context.Background()),
			IDao:        proxy[0].DaoConfig(context.Background()).Dao,
			ignoreCache: proxy[0].DaoConfig(context.Background()).IsIgnoreCache(),
			exWhereArr:  proxy[0].DaoConfig(context.Background()).Dao.GetExtWhereKeys(),
		}

		return dao
	}

	return &OssAppConfigDao{
		group:   "default",
		table:   "oss_app_config",
		columns: ossAppConfigColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OssAppConfigDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *OssAppConfigDao) Table() string {
	return dao.table
}

// Group returns the configuration group name of database of current dao.
func (dao *OssAppConfigDao) Group() string {
	return dao.group
}

// Columns returns all column names of current dao.
func (dao *OssAppConfigDao) Columns() OssAppConfigColumns {
	return dao.columns
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OssAppConfigDao) Ctx(ctx context.Context, cacheOption ...*gdb.CacheOption) *gdb.Model {
	return dao.DaoConfig(ctx, cacheOption...).Model
}

func (dao *OssAppConfigDao) DaoConfig(ctx context.Context, cacheOption ...*gdb.CacheOption) *dao_interface.DaoConfig {
	//if dao.daoConfig != nil && len(dao.exWhereArr) == 0 {
	//	return dao.daoConfig
	//}

	var daoConfig = daoctl.NewDaoConfig(ctx, dao, cacheOption...)
	dao.daoConfig = &daoConfig

	if len(dao.exWhereArr) > 0 {
		daoConfig.IgnoreExtModel(dao.exWhereArr...)
		dao.exWhereArr = []string{}

	}

	if dao.ignoreCache {
		daoConfig.IgnoreCache()
	}

	return dao.daoConfig
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OssAppConfigDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}

func (dao *OssAppConfigDao) GetExtWhereKeys() []string {
	return dao.exWhereArr
}

func (dao *OssAppConfigDao) IsIgnoreCache() bool {
	return dao.ignoreCache
}

func (dao *OssAppConfigDao) IgnoreCache() dao_interface.IDao {
	dao.ignoreCache = true
	return dao
}
func (dao *OssAppConfigDao) IgnoreExtModel(whereKey ...string) dao_interface.IDao {
	dao.exWhereArr = append(dao.exWhereArr, whereKey...)
	return dao
}
